### ISSUE TITLE
ETA: Fishing with Pirates Lost Ring equipped is broken

### ISSUE THREAD

**Issue by madasi** [gmiclotte/melvor-scripts#8]
On my system, fishing with the Pirate's List Ring equipped caused the tab to freeze and stop responding when ETA is loaded.

The changelog for Melvor v0.19.1 mentioned a fix to this ring:

[FIXED] Pirate's Lost Ring providing an inconsistent Skill XP bonus.

It looks like https://github.com/gmiclotte/melvor-scripts/blob/master/ETA/ETA.js#L1117 is looking for a fishingBonusXP attribute. 
`xpMultiplier += items[CONSTANTS.item.Pirates_Lost_Ring].fishingBonusXP / 100;` 
From what I can see, this isn't present any more and was replaced with modifiers, although I can't tell the syntax used in the new array well enough to propose a fix. 
`xpMultiplier += items[CONSTANTS.item.Pirates_Lost_Ring].modifiers.increasedSkillXP[0][1] / 100;`
would probably work, but doesn't scale to other items without knowing the schema used in the modifiers array. I don't see anything linking the 15 value to fishing XP for example.

```
modifiers:
  increasedSkillXP: Array(1)
    0: Array(2)
      0: undefined
      1: 15
```

The full item taken from my console in Chrome:

```
items[667]

attackBonus: (3) [0, 0, 0]
canEquip: true
category: "Fishing"
damageReduction: 0
defenceBonus: 0
description: "+15% Fishing XP when equipped."
equipmentSlot: 7
fishingCatchWeight: 10
hasStats: true
id: 667
magicAttackBonus: 0
magicDamageBonus: 0
magicDefenceBonus: 0
media: "assets/media/bank/pirates_lost_ring.svg"
modifiers:
  increasedSkillXP: Array(1)
    0: Array(2)
      0: undefined
      1: 15
      length: 2
      __proto__: Array(0)
    length: 1
    __proto__: Array(0)
  __proto__: Object
name: "Pirates Lost Ring"
rangedAttackBonus: 0
rangedDefenceBonus: 0
rangedStrengthBonus: 0
sellsFor: 17500
strengthBonus: 0
type: "Special"
__proto__: Object
```
